# Phân tích chẩn đoán

## 1. Chuẩn bị dữ liệu

In [1]:
# Load libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
customers = pd.read_csv("../data/2_clean/customers.csv")
orders = pd.read_csv("../data/2_clean/orders.csv")
order_items = pd.read_csv("../data/2_clean/order_items.csv")
payments = pd.read_csv("../data/2_clean/payments.csv")
products = pd.read_csv("../data/2_clean/products.csv")
reviews = pd.read_csv("../data/2_clean/reviews.csv")
geolocation = pd.read_csv("../data/2_clean/geolocation.csv")
sellers = pd.read_csv("../data/2_clean/sellers.csv")

## 2. Phân loại cảm xúc
**Mục tiêu:** phân loại các đánh giá dưới 3 sao theo `negative / positive / neutral`

In [3]:
reviews

,review_id,order_id,review_score,review_comment_message
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,Recebi bem antes do prazo estipulado.
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,Parabéns lojas lannister adorei comprar pela I...
...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,"Excelente mochila, entrega super rápida. Super..."
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,"meu produto chegou e ja tenho que devolver, po..."

In [4]:
df = reviews[(~reviews["review_comment_message"].isnull()) & (reviews["review_score"] < 3)]
display(df[["review_id", "review_comment_message"]])

,review_id,review_comment_message
16,9314d6f9799f5bfba510cc7bcd468c01,"GOSTARIA DE SABER O QUE HOUVE, SEMPRE RECEBI E..."
19,373cbeecea8286a2b66c97b1b157ec46,Péssimo
29,2c5e27fc178bde7ac173c9c62c31b070,Não gostei ! Comprei gato por lebre
32,58044bca115705a48fe0e00a21390c54,Sempre compro pela Internet e a entrega ocorre...
39,9fd59cd04b42f600df9f25e54082a8d1,Nada de chegar o meu pedido.
...,...,...
99155,2fc8295a24978092328d3a329d22940e,Eu recebi o seguinte email e preciso saber com...
99169,3450ec3bbabeb09a08b00fc72da87a30,Boa tarde. \r\nNão recebo todos os produtos fa...
99200,2ee221b28e5b6fceffac59487ed39348,Foto muito diferente principalmente a graninha...
99203,5085bc489aa6b58a29c4f922d59ff826,Tive um problema na entrega em que o correio c...
99223,efe49f1d6f951dd88b51e6ccd4cc548f,"meu produto chegou e ja tenho que devolver, po..."

In [5]:
#!pip install pysentimiento

In [6]:
#!pip install --upgrade accelerate

In [7]:
#!pip install --upgrade torch transformers

In [8]:
import accelerate
import torch
import transformers

print(accelerate.__version__)    # >=0.26.0
print(torch.__version__)         # >=2.0
print(transformers.__version__)  # >=4.13

c:\Users\sonvuuu\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

1.12.0
2.9.1+cpu
4.57.3

In [7]:
import pandas as pd
from pysentimiento import create_analyzer

# Tạo analyzer sentiment cho tiếng Bồ Đào Nha
analyzer = create_analyzer(task="sentiment", lang="pt")

# Hàm map label sang Positive / Neutral / Negative
def map_label(label):
    return {
        "NEG": "Negative",
        "NEU": "Neutral",
        "POS": "Positive"
    }.get(label, "Neutral")

# Batch size
batch_size = 32
sentiments = []

# Chia comment thành batch
comments = df['review_comment_message'].tolist()
for i in range(0, len(comments), batch_size):
    batch = comments[i:i+batch_size]
    results = analyzer.predict(batch)  # pysentimiento hỗ trợ batch
    sentiments.extend([map_label(r.output) for r in results])

# Gán kết quả vào DataFrame
df['sentiment'] = sentiments

# Hiển thị 5 dòng đầu
print(df.head())

c:\Users\sonvuuu\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Map: 100%|██████████| 32/32 [00:00<00:00, 2279.24 examples/s]
c:\Users\sonvuuu\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
Map: 100%|██████████| 32/32 [00:00<00:00, 2549.24 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2123.06 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2287.05 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2365.15 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2625.34 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2772.41 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2699.80 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2005.79 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1793.40 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2117.37 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2458.38 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2194.00 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2525.12 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2545.09 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2357.59 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2557.89 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1682.88 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2860.50 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2308.45 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2190.63 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2272.07 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2536.48 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2834.23 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2751.38 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2027.67 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2557.84 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2547.99 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2403.10 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2247.41 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2738.35 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2616.28 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 3012.47 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2886.71 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2262.07 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2413.51 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2676.22 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2405.64 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2526.07 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2884.11 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2564.64 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2614.70 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2780.33 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2775.62 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2778.60 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2787.03 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2689.57 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2282.07 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2734.06 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2635.39 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2364.65 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2267.31 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 3032.69 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2365.07 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2662.52 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2453.71 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2295.18 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2548.91 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1918.22 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2778.37 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2119.47 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2218.33 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2422.18 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 3038.59 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2051.32 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1483.46 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1453.50 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1512.01 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2461.27 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2430.47 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2410.95 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1399.17 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1296.86 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2437.57 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2365.20 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2703.17 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1899.35 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2122.96 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1979.52 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1650.61 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1439.83 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2447.09 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2365.32 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2426.12 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1373.69 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2629.55 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2165.82 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1442.67 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2051.10 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2129.63 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1792.87 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2168.26 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2320.42 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2116.46 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2074.11 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2495.54 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2780.50 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1368.58 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2774.99 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1359.30 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2456.99 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1532.17 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1671.64 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1498.62 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1514.77 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1717.90 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2497.96 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1301.15 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2271.87 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1715.53 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1884.87 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1605.17 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2342.94 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1374.35 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2041.02 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1301.57 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1833.80 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1901.15 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1311.07 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1449.87 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1567.32 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1597.66 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1839.33 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1503.91 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1544.21 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2201.70 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1706.00 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2774.76 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1583.88 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1872.33 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1895.22 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2519.43 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1349.25 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2447.67 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1352.74 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2221.12 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2044.44 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2024.00 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2104.62 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2307.34 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2267.38 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2616.79 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2741.21 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2700.56 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2307.26 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2572.35 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2642.24 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2111.64 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2373.98 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2486.62 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2114.90 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2016.92 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2448.29 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2038.36 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2172.44 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2303.42 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2090.81 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2340.86 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2548.71 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2868.45 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1745.97 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2214.30 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2816.50 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2218.77 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2657.09 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2826.77 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2067.75 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2365.40 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 759.72 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1919.48 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1154.70 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1059.71 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1165.84 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1462.88 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1349.76 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1493.43 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2128.72 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2435.81 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2324.68 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2392.09 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2180.03 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2440.50 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2508.32 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2031.48 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2542.44 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 3170.22 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 3018.10 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2554.29 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2623.54 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 3051.37 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2475.34 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2463.03 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2899.18 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2717.29 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2590.23 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2579.67 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2463.07 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2857.03 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2587.78 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2521.09 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2635.03 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2570.48 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2454.69 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2424.67 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2502.66 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2867.29 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2916.19 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2853.87 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2579.42 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2729.61 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2761.74 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2524.36 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 3006.87 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2262.30 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2210.55 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2004.93 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2064.60 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2652.00 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2570.97 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2503.88 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2779.99 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2754.82 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2129.66 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2192.38 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2833.27 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2881.51 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2875.21 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2258.53 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2272.07 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2760.83 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2563.36 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2607.08 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2760.77 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2553.61 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2774.76 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2857.40 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2253.64 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2652.89 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2829.39 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2882.31 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1456.21 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2368.95 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2529.83 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2621.18 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1623.22 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1391.02 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2547.36 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2363.65 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2775.90 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1461.18 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2061.97 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 3118.51 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1909.27 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2687.10 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2593.28 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1993.49 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2447.71 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2453.57 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1458.63 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2257.20 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2559.79 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2493.78 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2194.14 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2625.80 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2654.36 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1146.03 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1865.98 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1624.28 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2641.30 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1614.32 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2560.72 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2847.15 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1503.57 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 3039.08 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1732.45 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1706.84 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2655.73 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1645.35 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1775.37 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1724.30 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2298.68 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1591.82 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2978.58 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1660.99 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1708.95 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2362.90 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1784.98 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2846.37 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2178.54 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2180.63 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2639.48 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1385.37 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2124.40 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2736.12 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2195.90 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2202.75 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1302.91 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 3366.05 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2126.26 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2322.83 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1373.23 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2457.80 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 3043.69 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1552.33 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2553.95 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2056.57 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2029.24 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 3003.84 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2278.08 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1678.31 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2260.55 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 1710.02 examples/s]
Map: 100%|██████████| 32/32 [00:00<00:00, 2716.24 examples/s]

                           review_id                          order_id  \
16  9314d6f9799f5bfba510cc7bcd468c01  0dacf04c5ad59fd5a0cc1faa07c34e39
19  373cbeecea8286a2b66c97b1b157ec46  583174fbe37d3d5f0d6661be3aad1786
29  2c5e27fc178bde7ac173c9c62c31b070  0ce9a24111d850192a933fcaab6fbad3
32  58044bca115705a48fe0e00a21390c54  68e55ca79d04a79f20d4bfc0146f4b66
39  9fd59cd04b42f600df9f25e54082a8d1  3c314f50bc654f3c4e317b055681dff9

    review_score                             review_comment_message sentiment
16             2  GOSTARIA DE SABER O QUE HOUVE, SEMPRE RECEBI E...  Negative
19             1                                            Péssimo  Negative
29             1                Não gostei ! Comprei gato por lebre  Negative
32             1  Sempre compro pela Internet e a entrega ocorre...  Negative
39             1                       Nada de chegar o meu pedido.  Negative

C:\Users\sonvuuu\AppData\Local\Temp\ipykernel_10028\2771575334.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sentiment'] = sentiments

In [8]:
df

,review_id,order_id,review_score,review_comment_message,sentiment
16,9314d6f9799f5bfba510cc7bcd468c01,0dacf04c5ad59fd5a0cc1faa07c34e39,2,"GOSTARIA DE SABER O QUE HOUVE, SEMPRE RECEBI E...",Negative
19,373cbeecea8286a2b66c97b1b157ec46,583174fbe37d3d5f0d6661be3aad1786,1,Péssimo,Negative
29,2c5e27fc178bde7ac173c9c62c31b070,0ce9a24111d850192a933fcaab6fbad3,1,Não gostei ! Comprei gato por lebre,Negative
32,58044bca115705a48fe0e00a21390c54,68e55ca79d04a79f20d4bfc0146f4b66,1,Sempre compro pela Internet e a entrega ocorre...,Negative
39,9fd59cd04b42f600df9f25e54082a8d1,3c314f50bc654f3c4e317b055681dff9,1,Nada de chegar o meu pedido.,Negative
...,...,...,...,...,...
99155,2fc8295a24978092328d3a329d22940e,e809c167a9cfd31aee1293abe8995065,1,Eu recebi o seguinte email e preciso saber com...,Neutral
99169,3450ec3bbabeb09a08b00fc72da87a30,c46f950813dd2dd9bab4188dceb83175,1,Boa tarde. \r\nNão recebo todos os produtos fa...,Neutral
99200,2ee221b28e5b6fceffac59487ed39348,f2d12dd37eaef72ed7b1186b2edefbcd,2,Foto muito diferente principalmente a graninha...,Neutral
99203,5085bc489aa6b58a29c4f922d59ff826,18ed848509774f56cc8c1c0a1903ad7f,2,Tive um problema na entrega em que o correio c...,Negative
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,"meu produto chegou e ja tenho que devolver, po...",Negative

In [9]:
import os

# Lưu từng DataFrame
output_dir = "../data/3_sentiment"

df.to_csv(os.path.join(output_dir, "reviews_1.csv"), index=False)

In [43]:
df = pd.read_csv("../data/3_sentiment/reviews_1.csv")
df = df[df["sentiment"] == "Positive"]
df

,review_id,order_id,review_score,review_comment_message,sentiment
80,7b66de927426b71a817aa36df5e8a0b3,634e8f4c0f6744a626f77f39770ac6aa,1,Muito bom o produto e preço cobrado!,Positive
85,8bc4d875dbab927e9190060688edc80f,b6e5ddeaf2e5b56015e295beb333f305,2,Excelente produto indico a qualquer pessoa.,Positive
126,b42955e5003fa4e9449770fb8b50d30d,1f186ad4ad389666cd9482ce1942038d,2,Demorou mas entregou!,Positive
258,d04bfe3b90e5436b03b65e86d8b6e62d,9292f2ff747a4f8c6580fc8377bb1c8b,2,Apesar da demora na entrega. No mais foi tudo ...,Positive
314,488f5ad66f112743c91ae61731522375,5e3ec924bc1a1f3793e12632c2b2f85d,1,muito obrigado\r\n,Positive
...,...,...,...,...,...
10532,14876c10d791683465f83751ff33064d,296752c5e35a99dd06b9100ab400c8eb,2,Produto bom,Positive
10540,0ba0eb2b255cfe3925088677a49add35,cf5439c6b13deafe107ecca7dcc58b80,1,"paguei 80 rreais de frete, quero esse produro ...",Positive
10626,c0881b2797529c9af9325018e7fbb694,fd7eb2117233aa5ac29e94a28e082077,1,o produto era exatamente o que eu precisasa,Positive
10636,9740c39fe70be3fdd5b610c34358a278,be73d4698f2f4939662dd7788cf3dad3,2,Até as que dão no lava car e postos de gasolin...,Positive
10644,1a393495bf6472d5ee440d0d12099f98,dc8211dc85eb0da6c9f3155218cb4113,1,Gostei do produto.,Positive

## 3. Phân loại thể loại
**Mục tiêu:** phân loại các đánh giá dưới 3 sao theo `negative / positive / neutral`

In [59]:
df = pd.read_csv("../data/3_sentiment/reviews_1.csv")
df = df[df["sentiment"] != "Positive"]
df = df.head(20)
df

,review_id,order_id,review_score,review_comment_message,sentiment
0,9314d6f9799f5bfba510cc7bcd468c01,0dacf04c5ad59fd5a0cc1faa07c34e39,2,"GOSTARIA DE SABER O QUE HOUVE, SEMPRE RECEBI E...",Negative
1,373cbeecea8286a2b66c97b1b157ec46,583174fbe37d3d5f0d6661be3aad1786,1,Péssimo,Negative
2,2c5e27fc178bde7ac173c9c62c31b070,0ce9a24111d850192a933fcaab6fbad3,1,Não gostei ! Comprei gato por lebre,Negative
3,58044bca115705a48fe0e00a21390c54,68e55ca79d04a79f20d4bfc0146f4b66,1,Sempre compro pela Internet e a entrega ocorre...,Negative
4,9fd59cd04b42f600df9f25e54082a8d1,3c314f50bc654f3c4e317b055681dff9,1,Nada de chegar o meu pedido.,Negative
5,e233e51d11511bf30e568c76360ace52,548df2c6e5f089574614894bca78acf5,1,recebi somente 1 controle Midea Split ESTILO.\...,Negative
6,6d06808638ec0701bccd70bc8d462c28,97d2f8fe76f2f253b8291e17b5383884,1,O produto não chegou no prazo estipulado e cau...,Negative
7,60c714ed14cef913944a3147094a4742,9ac05114800f02bfaa783bd76842dbe2,1,"Produto muito inferior, mal acabado.",Negative
8,65dfeb60c40e3cbb0a1838285d86f885,a2714ecbf6eeb3bb9cd7dba6dc1c5e82,1,Pedi reembolso e sem resposta até momento,Negative
9,ae728c1061bf163b4bd256ad9ee0bb83,45c780334bc32cb77559a65c5f171160,1,Este foi o pedido\r\nBalde Com 128 Peças - Blo...,Neutral
10,72730619a00e0ecdecf0a4ff862d8996,af76a45a10524549102e010f2bd9d3cd,1,comprei tres pacotes de cinco folhas cada de p...,Neutral
11,5c37d7ba6ef2f031c34bb4fda3454018,bbd1b9ebbc5a09d51caaa2d10e0f93b5,2,Demorou de mais pra entrega,Negative
12,346317f9aff540395fe46893611854f8,546ffb713086001ce9f0009158f88b73,1,Não funciona não faz sincronismo,Negative
13,487f8ff16eaf366dc7c01652202048c3,d5ba80d74b52c335ae36398d6159e6ee,1,"Chegou apenas uma peça, mas na nota e na garan...",Neutral
14,ef8ae544c432bb1053ba5990bd0d6227,e18ebd6286697a3f0f6fe267d8286cb2,1,EU NÃO RECEBI O PRODUTO E CONSTA NO SISTEMA QU...,Negative
15,aaab917291fea34988b9a0cb60e0716f,560f7585b57fcc9579460fa21c0d8ec1,1,"Comprei o relógio, unissex e enviaram um relóg...",Neutral
16,5f938e5f5f2e9a75710b54feeb9ea610,d9ff0185a300435402f043124f530274,1,A peça não serviu,Negative
17,d7ea05bb4f9c77d606fd90b1a27e317d,bb5b0d8f3e9c964760c674f2aa2ae0cf,1,Comprei o produto dia 25 de fevereiro e hoje d...,Negative
18,185cb85ede91009d7a8e685687c037ee,2e5dc86c8c4aa663549caf5e31de840d,1,fiz minha compra faz 30 dias e não recebi aind...,Negative
19,c40a6b6e0181e5ec0d12cbc2e12c49d3,f3468d6a2c7586711e9952242898aad4,1,Faltou 1 produto e os que recebi 1 veio quebrado,Negative

In [48]:
import requests
import json

system_prompt = """
You are a strict classification engine.

Your task:
- Classify e-commerce user comments into EXACTLY ONE category.
- Focus ONLY on the main complaint or feedback.
- Ignore greetings, politeness, or irrelevant details.

Categories (choose ONE only):
1. Product Quality
   - Defects, broken items, poor quality, wrong product, missing parts

2. Delivery
   - Late delivery, shipping delay, lost package, damaged in transport

3. Customer Service
   - Rude staff, no response, bad support, cannot contact seller/platform

4. Other
   - Praise, neutral comments, unclear feedback, or anything not above

Rules:
- Always output EXACTLY one category name.
- Do NOT explain.
- Do NOT add punctuation.
- Do NOT output numbering.
- Do NOT output multiple labels.
- If unsure, choose "Other".
"""


def translate_comment():
    url = "http://172.30.224.1:1234/v1/responses"
    headers = {"Content-Type": "application/json"}  # nếu có token thì thêm Authorization
    payload = {
        "model": "llama-3-groq-8b-tool-use:2",  
        "input": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": 
                """Produto muito inferior, mal acabado."""}
        ]
    }

    response = requests.post(url, headers=headers, json=payload)

    # Format output
    data = response.json()["output"][0]["content"][0]["text"]

    return data

print(translate_comment())

Product Quality

In [60]:
import pandas as pd
import requests
import time

# ================== CONFIG ==================

URL = "http://172.30.224.1:1234/v1/responses"
MODEL = "llama-3-groq-8b-tool-use:2"

system_prompt = """
You are a strict classification engine.

Your task:
- Classify e-commerce user comments into EXACTLY ONE category.
- Focus ONLY on the main complaint or feedback.
- Ignore greetings, politeness, or irrelevant details.

Categories:
Product Quality
Delivery
Customer Service
Other

Rules:
- Output EXACTLY one category name
- Do NOT explain
- Do NOT add punctuation
- Do NOT add numbering
- Do NOT output multiple labels
- If unsure, choose Other
"""

# ================== CLASSIFY FUNCTION ==================

def classify_comment(text: str) -> str:
    payload = {
        "model": MODEL,
        "input": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": text}
        ]
    }

    try:
        res = requests.post(URL, json=payload, timeout=30)
        res.raise_for_status()
        label = res.json()["output"][0]["content"][0]["text"].strip()

        # Safety clamp
        if label not in ["Product Quality", "Delivery", "Customer Service", "Other"]:
            return "Other"

        return label

    except Exception as e:
        print("Error:", e)
        return "Other"


# ================== RUN (SAFE MODE) ==================

df["category"] = df["review_comment_message"].apply(classify_comment)

df

,review_id,order_id,review_score,review_comment_message,sentiment,category
0,9314d6f9799f5bfba510cc7bcd468c01,0dacf04c5ad59fd5a0cc1faa07c34e39,2,"GOSTARIA DE SABER O QUE HOUVE, SEMPRE RECEBI E...",Negative,Customer Service
1,373cbeecea8286a2b66c97b1b157ec46,583174fbe37d3d5f0d6661be3aad1786,1,Péssimo,Negative,Delivery
2,2c5e27fc178bde7ac173c9c62c31b070,0ce9a24111d850192a933fcaab6fbad3,1,Não gostei ! Comprei gato por lebre,Negative,Customer Service
3,58044bca115705a48fe0e00a21390c54,68e55ca79d04a79f20d4bfc0146f4b66,1,Sempre compro pela Internet e a entrega ocorre...,Negative,Delivery
4,9fd59cd04b42f600df9f25e54082a8d1,3c314f50bc654f3c4e317b055681dff9,1,Nada de chegar o meu pedido.,Negative,Delivery
5,e233e51d11511bf30e568c76360ace52,548df2c6e5f089574614894bca78acf5,1,recebi somente 1 controle Midea Split ESTILO.\...,Negative,Delivery
6,6d06808638ec0701bccd70bc8d462c28,97d2f8fe76f2f253b8291e17b5383884,1,O produto não chegou no prazo estipulado e cau...,Negative,Delivery
7,60c714ed14cef913944a3147094a4742,9ac05114800f02bfaa783bd76842dbe2,1,"Produto muito inferior, mal acabado.",Negative,Delivery
8,65dfeb60c40e3cbb0a1838285d86f885,a2714ecbf6eeb3bb9cd7dba6dc1c5e82,1,Pedi reembolso e sem resposta até momento,Negative,Delivery
9,ae728c1061bf163b4bd256ad9ee0bb83,45c780334bc32cb77559a65c5f171160,1,Este foi o pedido\r\nBalde Com 128 Peças - Blo...,Neutral,Delivery
10,72730619a00e0ecdecf0a4ff862d8996,af76a45a10524549102e010f2bd9d3cd,1,comprei tres pacotes de cinco folhas cada de p...,Neutral,Delivery
11,5c37d7ba6ef2f031c34bb4fda3454018,bbd1b9ebbc5a09d51caaa2d10e0f93b5,2,Demorou de mais pra entrega,Negative,Product Quality
12,346317f9aff540395fe46893611854f8,546ffb713086001ce9f0009158f88b73,1,Não funciona não faz sincronismo,Negative,Product Quality
13,487f8ff16eaf366dc7c01652202048c3,d5ba80d74b52c335ae36398d6159e6ee,1,"Chegou apenas uma peça, mas na nota e na garan...",Neutral,Delivery
14,ef8ae544c432bb1053ba5990bd0d6227,e18ebd6286697a3f0f6fe267d8286cb2,1,EU NÃO RECEBI O PRODUTO E CONSTA NO SISTEMA QU...,Negative,Customer Service
15,aaab917291fea34988b9a0cb60e0716f,560f7585b57fcc9579460fa21c0d8ec1,1,"Comprei o relógio, unissex e enviaram um relóg...",Neutral,Customer Service
16,5f938e5f5f2e9a75710b54feeb9ea610,d9ff0185a300435402f043124f530274,1,A peça não serviu,Negative,Product Quality
17,d7ea05bb4f9c77d606fd90b1a27e317d,bb5b0d8f3e9c964760c674f2aa2ae0cf,1,Comprei o produto dia 25 de fevereiro e hoje d...,Negative,Delivery
18,185cb85ede91009d7a8e685687c037ee,2e5dc86c8c4aa663549caf5e31de840d,1,fiz minha compra faz 30 dias e não recebi aind...,Negative,Delivery
19,c40a6b6e0181e5ec0d12cbc2e12c49d3,f3468d6a2c7586711e9952242898aad4,1,Faltou 1 produto e os que recebi 1 veio quebrado,Negative,Delivery

### 1. Chẩn đoán "Nội dung đánh giá"
**Mục tiêu**: Giải mã lý do thực sự đằng sau các con số 1 sao, 2 sao. Dữ liệu số (Rating) chỉ cho biết mức độ, dữ liệu chữ (Comment) mới cho biết nguyên nhân.
- Trong số các đánh giá tiêu cực (1-2 sao), bao nhiêu % nhắc đến từ khóa liên quan "logistics" (chậm, chưa nhận được), bao nhiêu % liên quan đến "product" (hỏng, sai màu, hàng giả)?
- Có trường hợp nào khách đánh giá 5 sao nhưng comment phàn nàn (hoặc ngược lại) không? Tại sao?
- Những chủ đề (Topic) chính mà khách hàng thường thảo luận là gì? (Ví dụ: Topic 1: Giao hàng, Topic 2: Chất lượng, Topic 3: Dịch vụ CSKH).