# Khám Phá Và Xử Lý Dữ Liệu Coronavirus

Notebook này thực hiện khám phá và xử lý dữ liệu từ dataset COVID-19 trên Our World in Data: [https://ourworldindata.org/coronavirus](https://ourworldindata.org/coronavirus).


## Thư viện cần thiết
- pandas: Xử lý dữ liệu

In [1]:
import pandas as pd
import numpy as np

# Thiết lập hiển thị cho pandas
pd.set_option('display.max_columns', None)

## 1. Import Thư Viện Và Nạp Dữ Liệu Vào Notebook

Đọc file CSV và chọn các cột cần thiết.

In [5]:
# Đọc dữ liệu từ URL
url = 'https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv'
coronavirus_data = pd.read_csv(url)

# Chọn các cột cần thiết theo yêu cầu
selected_columns = ['location', 'date', 'new_cases']
coronavirus_data = coronavirus_data[selected_columns]

# Hiển thị thông tin cơ bản
print('Số hàng và cột:', coronavirus_data.shape)
print('\nThông tin dữ liệu:')
print(coronavirus_data.info())
print('\n5 hàng đầu:')
display(coronavirus_data.head())

Số hàng và cột: (429435, 3)

Thông tin dữ liệu:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 429435 entries, 0 to 429434
Data columns (total 3 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   location   429435 non-null  object
 1   date       429435 non-null  object
 2   new_cases  410159 non-null  float64
dtypes: float64(1), object(2)
memory usage: 9.8+ MB
None

5 hàng đầu:

      location        date  new_cases
0  Afghanistan  2020-01-05        0.0
1  Afghanistan  2020-01-06        0.0
2  Afghanistan  2020-01-07        0.0
3  Afghanistan  2020-01-08        0.0
4  Afghanistan  2020-01-09        0.0

## 2. Loại Bỏ Dữ Liệu Trùng Lặp

Kiểm tra và loại bỏ duplicates, xóa hàng/cột cụ thể.

In [6]:
# Hiển thị head() để xem dữ liệu gốc
print('Dữ liệu gốc (head()):')
display(coronavirus_data.head())

# Loại bỏ duplicates trên toàn bộ cột
coronavirus_data_duplicate = coronavirus_data.drop_duplicates()
print(f'\nSố hàng sau khi drop duplicates: {len(coronavirus_data_duplicate)}')

# Xóa một hàng cụ thể tại index 1 (ví dụ)
coronavirus_data_no_row = coronavirus_data.drop(labels=[1], axis=0)
print(f'Số hàng sau khi xóa row index 1: {len(coronavirus_data_no_row)}')

# Xóa một cột cụ thể (ví dụ: date)
coronavirus_data_no_col = coronavirus_data.drop(labels=['date'], axis=1)
print(f'Số cột sau khi xóa cột date: {len(coronavirus_data_no_col.columns)}')
print('\nDữ liệu sau khi xóa cột (head()):')
display(coronavirus_data_no_col.head())

Dữ liệu gốc (head()):

      location        date  new_cases
0  Afghanistan  2020-01-05        0.0
1  Afghanistan  2020-01-06        0.0
2  Afghanistan  2020-01-07        0.0
3  Afghanistan  2020-01-08        0.0
4  Afghanistan  2020-01-09        0.0

Số hàng sau khi drop duplicates: 429435
Số hàng sau khi xóa row index 1: 429434
Số cột sau khi xóa cột date: 2

Dữ liệu sau khi xóa cột (head()):

      location  new_cases
0  Afghanistan        0.0
1  Afghanistan        0.0
2  Afghanistan        0.0
3  Afghanistan        0.0
4  Afghanistan        0.0

## 3. Thay Thế Dữ Liệu Và Thay Đổi Định Dạng Của Dữ Liệu

Thay thế giá trị trong new_cases, fill NA trong new_cases, và thay đổi kiểu dữ liệu.

In [7]:
# Thay thế giá trị trong new_cases: NaN hoặc 0 -> 'no cases', >0 -> 'has cases'
coronavirus_data['new_cases_replaced'] = np.where(coronavirus_data['new_cases'].isna() | (coronavirus_data['new_cases'] == 0), 
                                                  'no cases', 'has cases')
print('Cột new_cases_replaced (head()):')
display(coronavirus_data[['new_cases', 'new_cases_replaced']].head())

# Fill NA trong cột new_cases bằng 0
print(f'\nSố NA trong new_cases trước: {coronavirus_data["new_cases"].isnull().sum()}')
coronavirus_data['new_cases'] = coronavirus_data['new_cases'].fillna(0)
print(f'Số NA trong new_cases sau: {coronavirus_data["new_cases"].isnull().sum()}')

# Thay đổi kiểu dữ liệu của new_cases từ float sang int
coronavirus_data['new_cases_changed'] = coronavirus_data['new_cases'].astype(int)
print('\nKiểu dữ liệu new_cases_changed:')
print(coronavirus_data['new_cases_changed'].dtype)
print('\nnew_cases_changed (head()):')
display(coronavirus_data[['new_cases', 'new_cases_changed']].head())

Cột new_cases_replaced (head()):

   new_cases new_cases_replaced
0        0.0           no cases
1        0.0           no cases
2        0.0           no cases
3        0.0           no cases
4        0.0           no cases

Số NA trong new_cases trước: 19276
Số NA trong new_cases sau: 0

Kiểu dữ liệu new_cases_changed:
int64

new_cases_changed (head()):

   new_cases  new_cases_changed
0        0.0                  0
1        0.0                  0
2        0.0                  0
3        0.0                  0
4        0.0                  0

## 4. Xử Lý Dữ Liệu Thiếu

Kiểm tra và loại bỏ missing values.

In [9]:
# Kiểm tra missing values bằng isnull().sum()
print('Số lượng missing values theo cột:')
missing_summary = coronavirus_data.isnull().sum()
display(missing_summary)

# Loại bỏ missing values (how='any' để xóa nếu bất kỳ cột nào có NA)
coronavirus_data_withoutna = coronavirus_data.dropna(how='any')
print(f'\nShape dữ liệu gốc: {coronavirus_data.shape}')
print(f'Shape dữ liệu sau dropna: {coronavirus_data_withoutna.shape}')

# Hiển thị head() của dữ liệu sạch
print('\nDữ liệu sau xử lý missing (head()):')
display(coronavirus_data_withoutna.head())

Số lượng missing values theo cột:

location              0
date                  0
new_cases             0
new_cases_replaced    0
new_cases_changed     0
dtype: int64

Shape dữ liệu gốc: (429435, 5)
Shape dữ liệu sau dropna: (429435, 5)

Dữ liệu sau xử lý missing (head()):

      location        date  new_cases new_cases_replaced  new_cases_changed
0  Afghanistan  2020-01-05        0.0           no cases                  0
1  Afghanistan  2020-01-06        0.0           no cases                  0
2  Afghanistan  2020-01-07        0.0           no cases                  0
3  Afghanistan  2020-01-08        0.0           no cases                  0
4  Afghanistan  2020-01-09        0.0           no cases                  0

## 5. Tính toán thống kê mô tả

In [ ]:


import numpy as np
import pandas as pd
from scipy import stats

# Sử dụng dữ liệu đã có sẵn trong biến coronavirus_data
covid_data = coronavirus_data

# Take a quick look at the data
print(covid_data.head(5))
print(covid_data.dtypes)
print(covid_data.shape)

# Get the mean of the data
data_mean = np.mean(covid_data["new_cases"])
# Get the median of the data
data_median = np.median(covid_data["new_cases"])
# Get the mode of the data
data_mode = stats.mode(covid_data["new_cases"], keepdims=True)[0][0]
# Obtain the variance of the data
data_variance = np.var(covid_data["new_cases"])
# Obtain the standard deviation of the data
data_sd = np.std(covid_data["new_cases"])
# Compute the maximum and minimum values of the data
data_max = np.max(covid_data["new_cases"])
data_min = np.min(covid_data["new_cases"])
# Obtain the 60th percentile of the data
data_percentile = np.percentile(covid_data["new_cases"], 60)
# Obtain the quartiles of the data
data_quartile = np.quantile(covid_data["new_cases"], 0.75)
# Get the IQR of the data
data_IQR = stats.iqr(covid_data["new_cases"])

print("Thống kê mô tả cho 'new_cases' trong covid_data:")
print(f"Mean: {data_mean}")
print(f"Median: {data_median}")
print(f"Mode: {data_mode}")
print(f"Variance: {data_variance}")
print(f"Standard deviation: {data_sd}")
print(f"Max: {data_max}")
print(f"Min: {data_min}")
print(f"60th percentile: {data_percentile}")
print(f"Q3 (75th percentile): {data_quartile}")
print(f"IQR: {data_IQR}")

      location        date  new_cases new_cases_replaced  new_cases_changed
0  Afghanistan  2020-01-05        0.0           no cases                  0
1  Afghanistan  2020-01-06        0.0           no cases                  0
2  Afghanistan  2020-01-07        0.0           no cases                  0
3  Afghanistan  2020-01-08        0.0           no cases                  0
4  Afghanistan  2020-01-09        0.0           no cases                  0
location               object
date                   object
new_cases             float64
new_cases_replaced     object
new_cases_changed       int64
dtype: object
(429435, 5)
Thống kê mô tả cho 'new_cases' trong covid_data:
Mean: 7657.48561016219
Median: 0.0
Mode: 0.0
Variance: 50380982412.89473
Standard deviation: 224457.08367724714
Max: 44236227.0
Min: 0.0
60th percentile: 0.0
Q3 (75th percentile): 0.0
IQR: 0.0

## Kết Luận

- Dữ liệu đã được tải và chọn cột thành công.
- Đã loại bỏ duplicates và các hàng/cột không cần thiết.
- Thay thế và thay đổi định dạng dữ liệu cho phù hợp.
- Xử lý missing values bằng cách fill và dropna.